export const columnsReff = [
  {
    value: "headgear",
    text: "Headgear",
    meta: {
      readyHashtag: "#thriftcapready",
      altTag: "topi",
      extraCaption: "SIZE : -\n",
      hashtag: [
        "topi#brand#",
        "topi#brand#second",
        "topi#brand#vintage",
        "topi#design#",
        "snapback#design#",
        "snapback#brand#",
        "snapback#brand#second",
        "cap#brand#",
        "cap#brand#second",
        "cap#design#",
        "5panel#brand#",
        "5panel#brand#second",
        "trucker#brand#",
        "trucker#brand#second",
        "trucker#brand#",
        "trucker#design#",
        "topi#brand##design#",
        "#brand##design#second",
        "#brand##design#",
        "snapback#brand##design#",
        "#brand#",
        "#design#",
        "topivintage",
        "snapbackvintage",
        "topisecondbranded",
        "topisecond",
        "topibekas",
        "snapbacksecond",
        "capsecond",
      ],
    },
  },
  {
    value: "tshirt",
    text: "T-Shirt",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "kaos",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "tshirt#brand#",
        "tshirt#design#",
        "tshirt#brand##design#",
        "tee#brand#",
        "tee#design#",
        "tee#brand##design#",
        "kaos#brand#",
        "kaos#design#",
        "kaos#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "kaossecond",
        "kaossecondbranded",
      ],
    },
  },
  {
    value: "shirt",
    text: "Shirt",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "kemeja",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "shirt#brand#",
        "shirt#design#",
        "shirt#brand##design#",
        "flannel#brand#",
        "flannel#design#",
        "flannel#brand##design#",
        "kemeja#brand#",
        "kemeja#design#",
        "kemeja#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "kemejasecond",
        "kemejasecondbranded",
      ],
    },
  },
  {
    value: "crewneck",
    text: "Crewneck",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "crewneck",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "crewneck#brand#",
        "crewneck#design#",
        "crewneck#brand##design#",
        "outer#brand#",
        "outer#design#",
        "outer#brand##design#",
        "sweatshirt#brand#",
        "sweatshirt#design#",
        "sweatshirt#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "crewnecksecond",
        "crewnecksecondbranded",
      ],
    },
  },
  {
    value: "polo",
    text: "Polo",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "polo shirt",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "polo#brand#",
        "polo#design#",
        "polo#brand##design#",
        "kaoskerah#brand#",
        "kaoskerah#design#",
        "kaoskerah#brand##design#",
        "golfshirt#brand#",
        "golfshirt#design#",
        "golfshirt#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "polosecond",
        "polosecondbranded",
      ],
    },
  },
  {
    value: "hoodie",
    text: "Hoodie",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "Hoodie",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "hoodie#brand#",
        "hoodie#design#",
        "hoodie#brand##design#",
        "sweater#brand#",
        "sweater#design#",
        "sweater#brand##design#",
        "jacket#brand#",
        "jacket#design#",
        "jacket#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "hoodiesecond",
        "hoodiesecondbranded",
      ],
    },
  },
  {
    value: "tanktop",
    text: "Tank Top",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "Tank Top",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "tanktop#brand#",
        "tanktop#design#",
        "tanktop#brand##design#",
        "vest#brand#",
        "vest#design#",
        "vest#brand##design#",
        "singlet#brand#",
        "singlet#design#",
        "singlet#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "tanktopsecond",
        "tanktopsecondbranded",
      ],
    },
  },
  {
    value: "jersey",
    text: "Jersey",
    meta: {
      readyHashtag: "#readyroomthrift",
      altTag: "Jersey",
      extraCaption: "PANJANG : -\nLEBAR : -\nSIZE: -\n",
      hashtag: [
        "jersey#brand#",
        "jersey#design#",
        "jersey#brand##design#",
        "tshirt#brand#",
        "tshirt#design#",
        "tshirt#brand##design#",
        "tee#brand#",
        "tee#design#",
        "tee#brand##design#",
        "jual#brand#",
        "jual#design#",
        "jual#brand##design#",
        "#brand#second",
        "#brand#vintage",
        "thrift#brand#",
        "thrift#design#",
        "thrift#brand##design#",
        "#brand#",
        "#design#",
        "#brand##design#",
        "#brand#original",
        "jual#brand#second",
        "jual#brand#original",
        "vintage#brand#",
        "#brand#vintage",
        "secondbrand",
        "secondbranded",
        "jerseysecond",
        "jerseysecondbranded",
      ],
    },
  },
];
